export {
  createHealer,
  Healer,
  type CandidateCollector,
  type CreateHealerOptions,
} from './healer.js';
export {
  AUDIT_ATTACHMENT_CONTENT_TYPE,
  AUDIT_ATTACHMENT_PREFIX,
  AUDIT_SCHEMA_VERSION,
  AUDIT_PROVENANCE_VERSION,
  CompositeAuditSink,
  InMemoryAuditSink,
  JsonlAuditSink,
  NoopAuditSink,
  PlaywrightAttachmentAuditSink,
  createHealingAuditEvent,
  createHealingExecutionAuditEvent,
  createAuditProvenance,
  createPlaywrightAuditProvenance,
  parseAuditProvenance,
  type AuditProvenance,
  type AuditProvenanceInput,
  type AuditCollectionStatus,
  type AuditModeDecision,
  type AuditRankedCandidate,
  type AuditSink,
  type PlaywrightAuditProvenanceOptions,
  type HealwrightAuditEvent,
  type HealingAuditEvent,
  type HealingExecutionAuditEvent,
  type HealingExecutionReason,
  type HealingExecutionStatus,
} from './audit.js';
export {
  FileScreenshotCapture,
  type CapturedScreenshot,
  type ScreenshotCapture,
  type ScreenshotCaptureOptions,
  type ScreenshotPhase,
} from './artifacts.js';
export {
  collectCandidates,
  parseAriaIdentity,
  type AriaIdentity,
  type CandidateSnapshot,
} from './candidates.js';
export { executePrimaryAction, type PrimaryLocatorProbe } from './classification.js';
export {
  ArtifactCaptureError,
  AuditEvidenceError,
  AuditWriteError,
  HealingResultWriteError,
  MissingPrimaryLocatorError,
  RegistryValidationError,
  ProposalHistoryError,
  ProposalBundleValidationError,
  TargetActionNotAllowedError,
  UnknownTargetError,
} from './errors.js';
export {
  AUDIT_EVIDENCE_SUMMARY_SCHEMA_VERSION,
  auditEventsFromAttachments,
  canonicalizeAuditEvents,
  createAuditEvidenceSummary,
  serializeAuditHistory,
  writeAuditEvidence,
  type AuditAttachment,
  type AuditEvidenceSummary,
  type AuditEvidenceTargetSummary,
  type WriteAuditEvidenceOptions,
} from './evidence.js';
export {
  DEFAULT_PROPOSAL_MINIMUM_OBSERVATIONS,
  HEALING_PROPOSAL_SCHEMA_URL,
  HEALING_PROPOSAL_SCHEMA_VERSION,
  generateHealingProposals,
  loadAuditHistory,
  parseAuditHistory,
  renderHealingProposalReport,
  verifyHealingProposal,
  type GenerateHealingProposalOptions,
  type HealingProposal,
  type HealingProposalBundle,
  type HealingProposalEvidence,
  type HealingProposalRejection,
  type HealingProposalRejectionReason,
  type HealingProposalVerification,
} from './proposals.js';
export {
  loadHealingProposalBundle,
  parseHealingProposalBundle,
  verifyHealingProposalBundle,
  type HealingProposalBundleVerification,
  type HealingProposalVerificationIssue,
} from './proposal-validation.js';
export {
  ConsoleHealingResultSink,
  InMemoryHealingResultSink,
  NoopHealingResultSink,
  PASSED_WITH_HEALING,
  PlaywrightHealingResultSink,
  type HealingResultSink,
  type HealingSuccessResult,
} from './result.js';
export { resolvePrimaryLocator } from './locator.js';
export {
  CANDIDATE_ELIGIBILITY_REASONS,
  SCORE_WEIGHTS,
  assessCandidates,
  evaluateCandidateEligibility,
  rankCandidates,
  scoreCandidate,
  type CandidateAssessment,
  type CandidateAssessmentReason,
  type CandidateEligibility,
  type CandidateEligibilityReason,
  type RankedCandidate,
  type ScoreDetail,
  type ScoreSignal,
} from './scoring.js';
export { SUPPORTED_ARIA_ROLES, loadTargetRegistry, parseTargetRegistry } from './registry.js';
export { HEALING_MODES, TARGET_ACTIONS } from './types.js';
export type {
  AriaRole,
  HealingPolicy,
  HealingMode,
  PrimaryLocatorDefinition,
  TargetAction,
  TargetDefinition,
  TargetFingerprint,
  TargetGeometry,
  TargetPolicy,
  TargetRegistry,
} from './types.js';
